spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/fruity
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: PostgreSQL
  jpa:
    defer-datasource-initialization: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: public
        format_sql: true
    generate-ddl: false
    show-sql: true