spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: PostgreSQL
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: fruity
    generate-ddl: false