package hr.algebra.fruity.model.codebook;

public enum EmployeePrivileges {

  PRIVILEGE_CREATE_ARCODE_PARCEL(1),
  PRIVILEGE_READ_ARCODE_PARCEL(2),
  PRIVILEGE_UPDATE_ARCODE_PARCEL(3),
  PRIVILEGE_DELETE_ARCODE_PARCEL(4),
  PRIVILEGE_CREATE_CADASTRAL_PARCEL(5),
  PRIVILEGE_READ_CADASTRAL_PARCEL(6),
  PRIVILEGE_UPDATE_CADASTRAL_PARCEL(7),
  PRIVILEGE_DELETE_CADASTRAL_PARCEL(8),
  PRIVILEGE_CREATE_EMPLOYEE(9),
  PRIVILEGE_READ_EMPLOYEE(10),
  PRIVILEGE_UPDATE_EMPLOYEE(11),
  PRIVILEGE_DELETE_EMPLOYEE(12),
  PRIVILEGE_CREATE_ROW(13),
  PRIVILEGE_READ_ROW(14),
  PRIVILEGE_UPDATE_ROW(15),
  PRIVILEGE_DELETE_ROW(16),
  PRIVILEGE_CREATE_ROW_CLUSTER(17),
  PRIVILEGE_READ_ROW_CLUSTER(18),
  PRIVILEGE_UPDATE_ROW_CLUSTER(19),
  PRIVILEGE_DELETE_ROW_CLUSTER(20);

  private final Integer id;

  EmployeePrivileges(Integer id) {
    this.id = id;
  }

  public Integer id() {
    return id;
  }

  @Override
  public String toString() {
    return name();
  }
}
